const unavailableMetric = (label, reason = 'building_history') => ({
  available: false,
  value: null,
  label,
  reason_codes: [reason],
  evidence: {},
});

const availableMetrics = () => ({
  max_pain: { available: true, value: 0, label: 'Max Pain', reason_codes: [], evidence: {} },
  net_gex: { available: true, value: 120000, label: 'Estimated Net GEX', reason_codes: [], evidence: {} },
  gamma_flip: { available: true, value: 198, label: 'Estimated Gamma Flip', reason_codes: [], evidence: {} },
  call_wall: { available: true, value: 210, label: 'Estimated Call Wall', reason_codes: [], evidence: {} },
  put_wall: { available: true, value: 185, label: 'Estimated Put Wall', reason_codes: [], evidence: {} },
  atm_iv: { available: true, value: 0.32, label: 'ATM IV', reason_codes: [], evidence: {} },
  skew_25_delta: unavailableMetric('25-Delta Skew'),
  realized_volatility: unavailableMetric('Realized Volatility'),
  vrp: unavailableMetric('Volatility Risk Premium'),
  activity_intensity: { available: true, value: 0.75, label: 'Activity Intensity', reason_codes: [], evidence: {} },
  call_put_volume_ratio: { available: true, value: 1.2, label: 'Call / Put Volume', reason_codes: [], evidence: {} },
  volume_oi_ratio: { available: true, value: 0.305, label: 'Volume / Open Interest', reason_codes: [], evidence: {} },
  near_spot_volume_concentration: { available: true, value: 0.6, label: 'Near-Spot Volume Concentration', reason_codes: [], evidence: {} },
  near_spot_open_interest_concentration: { available: true, value: 0.55, label: 'Near-Spot Open Interest Concentration', reason_codes: [], evidence: {} },
});

const buildingHistoricalMetrics = () => ({
  iv_percentile: unavailableMetric('ATM IV Percentile'),
  iv_rank: unavailableMetric('ATM IV Rank'),
  max_pain_change_5: unavailableMetric('5-Observation Max Pain Change'),
  net_gex_change_5: unavailableMetric('5-Observation Net GEX Change'),
  gamma_flip_change_5: unavailableMetric('5-Observation Gamma Flip Change'),
  atm_iv_change_5: unavailableMetric('5-Observation ATM IV Change'),
  skew_25_delta_change_5: unavailableMetric('5-Observation 25-Delta Skew Change'),
  realized_volatility_change_5: unavailableMetric('5-Observation Realized Volatility Change'),
  vrp_change_5: unavailableMetric('5-Observation Volatility Risk Premium Change'),
  activity_intensity_change_5: unavailableMetric('5-Observation Activity Intensity Change'),
});

const availableHistoricalMetrics = () => ({
  ...buildingHistoricalMetrics(),
  iv_percentile: { available: true, value: 0.8, label: 'ATM IV Percentile', reason_codes: [], evidence: {} },
  iv_rank: { available: true, value: 0.7, label: 'ATM IV Rank', reason_codes: [], evidence: {} },
  max_pain_change_5: { available: true, value: 5, label: '5-Observation Max Pain Change', reason_codes: [], evidence: {} },
  atm_iv_change_5: { available: true, value: 0.03, label: '5-Observation ATM IV Change', reason_codes: [], evidence: {} },
});

export const commandCenterFixture = {
  schema_version: 'options-analytics-v1',
  calculation_version: 'options-analytics-v1',
  run_id: 7,
  source_feature_run_id: 33,
  source_as_of_date: '2026-09-04',
  market: 'US',
  provider: 'yahoo',
  started_at: '2026-09-04T21:00:00Z',
  published_at: '2026-09-04T21:40:00Z',
  latest_observation_at: '2026-09-04T21:30:00Z',
  expected_count: 2,
  current_count: 2,
  continuity_count: 0,
  completed_count: 2,
  core_valid_current_count: 2,
  failed_count: 0,
  retried_count: 1,
  coverage: 1,
  stale: false,
  reason_codes: [],
  assumptions: { risk_free_rate: 0.04 },
  items: [
    {
      symbol: 'AAPL',
      source_badges: ['candidate', 'leader'],
      candidate_rank: 1,
      leader_rank: 2,
      state: 'building_history',
      core_valid: true,
      spot_price: 200,
      expiration: '2026-10-16',
      observation_at: '2026-09-04T21:30:00Z',
      call_open_interest: 1000,
      put_open_interest: 800,
      call_volume: 300,
      put_volume: 250,
      activity_rank: 1,
      short_history_observation_count: 4,
      iv_history_observation_count: 4,
      lifetime_observation_count: 8,
      retry_count: 1,
      quality_evidence: {
        source_spot_price: 200,
        provider_spot_price: 201,
        spot_disagreement_ratio: 0.005,
        latest_contract_trade_at: '2026-09-04T20:00:00Z',
        days_to_expiration: 42,
        normalized_call_count: 30,
        normalized_put_count: 30,
        distinct_strike_count: 30,
        open_interest_coverage: 1,
        iv_coverage: 0.95,
        volume_coverage: 0.9,
        two_sided_quote_coverage: 0.85,
      },
      metrics: availableMetrics(),
      historical_metrics: buildingHistoricalMetrics(),
      assumptions: { gex_model: 'dealer_proxy' },
      warnings: [],
      reason_codes: ['building_history'],
    },
    {
      symbol: 'MSFT',
      source_badges: ['candidate'],
      candidate_rank: 2,
      leader_rank: null,
      state: 'available',
      core_valid: true,
      spot_price: 500,
      expiration: '2026-10-16',
      observation_at: '2026-09-04T21:29:00Z',
      call_open_interest: 900,
      put_open_interest: 700,
      call_volume: 200,
      put_volume: 180,
      activity_rank: 2,
      short_history_observation_count: 5,
      iv_history_observation_count: 5,
      lifetime_observation_count: 5,
      retry_count: 0,
      quality_evidence: {
        source_spot_price: 500,
        provider_spot_price: 500,
        spot_disagreement_ratio: 0,
        latest_contract_trade_at: '2026-09-04T20:00:00Z',
        days_to_expiration: 42,
        normalized_call_count: 30,
        normalized_put_count: 30,
        distinct_strike_count: 30,
        open_interest_coverage: 1,
        iv_coverage: 0.95,
        volume_coverage: 0.9,
        two_sided_quote_coverage: 0.85,
      },
      metrics: availableMetrics(),
      historical_metrics: availableHistoricalMetrics(),
      assumptions: {},
      warnings: [],
      reason_codes: [],
    },
  ],
};

export const symbolDetailFixture = {
  ...commandCenterFixture,
  items: undefined,
  item: commandCenterFixture.items[0],
  strike_points: [
    {
      strike: 195,
      call_open_interest: 500,
      put_open_interest: 400,
      call_volume: 100,
      put_volume: 80,
      call_iv: 0.31,
      put_iv: 0.33,
      estimated_call_gex: 1250,
      estimated_put_gex: -900,
    },
  ],
  history: [
    { as_of_date: '2026-08-31', state: 'available', max_pain: 188, net_gex: 100000 },
    { as_of_date: '2026-09-04', state: 'available', max_pain: 0, net_gex: 120000 },
  ],
};
delete symbolDetailFixture.items;

export const optionsManifestFixture = {
  schema_version: 'static-options-v1',
  data_schema_version: 'options-analytics-v1',
  calculation_version: 'options-analytics-v1',
  published_run_id: 7,
  source_feature_run_id: 33,
  source_as_of_date: '2026-09-04',
  market: 'US',
  provider: 'yahoo',
  generated_at: '2026-09-04T22:00:00Z',
  latest_observation_at: '2026-09-04T21:30:00Z',
  coverage: 1,
  stale: false,
  stale_relative_to_equity: false,
  reason_codes: [],
  command_center_path: 'options/command-center.json',
  symbols: {
    AAPL: { key: 'QUFQTA', path: 'options/symbols/QUFQTA.json' },
    MSFT: { key: 'TVNGVA', path: 'options/symbols/TVNGVA.json' },
  },
};
