export const buildDefaultScanFilters = () => ({
  symbolSearch: '',
  stage: null,
  ratings: [],
  ibdIndustries: { values: [], mode: 'include' },
  gicsSectors: { values: [], mode: 'include' },
  minVolume: null,
  minMarketCap: null,
  compositeScore: { min: null, max: null },
  minerviniScore: { min: null, max: null },
  canslimScore: { min: null, max: null },
  ipoScore: { min: null, max: null },
  customScore: { min: null, max: null },
  volBreakthroughScore: { min: null, max: null },
  seSetupScore: { min: null, max: null },
  seDistanceToPivot: { min: null, max: null },
  seBbSqueeze: { min: null, max: null },
  seVolumeVs50d: { min: null, max: null },
  seSetupReady: null,
  seRsLineNewHigh: null,
  rsRating: { min: null, max: null },
  rs1m: { min: null, max: null },
  rs3m: { min: null, max: null },
  rs12m: { min: null, max: null },
  epsRating: { min: null, max: null },
  price: { min: null, max: null },
  adrPercent: { min: null, max: null },
  epsGrowth: { min: null, max: null },
  salesGrowth: { min: null, max: null },
  vcpScore: { min: null, max: null },
  vcpPivot: { min: null, max: null },
  vcpDetected: null,
  vcpReady: null,
  maAlignment: null,
  passesTemplate: null,
  perfDay: { min: null, max: null },
  perfWeek: { min: null, max: null },
  perfMonth: { min: null, max: null },
  perf3m: { min: null, max: null },
  perf6m: { min: null, max: null },
  gapPercent: { min: null, max: null },
  volumeSurge: { min: null, max: null },
  ema10Distance: { min: null, max: null },
  ema20Distance: { min: null, max: null },
  ema50Distance: { min: null, max: null },
  week52HighDistance: { min: null, max: null },
  week52LowDistance: { min: null, max: null },
  ipoAfter: null,
  beta: { min: null, max: null },
  betaAdjRs: { min: null, max: null },
});
