"""Unified LLM package exports for sanctioned provider routing."""

from .llm_service import (
    LLMService,
    LLMError,
    LLMRateLimitError,
    LLMQuotaExceededError,
    LLMContextWindowError,
    quick_completion,
)
from .groq_key_manager import GroqKeyManager, get_groq_key_manager
from .zai_key_manager import ZAIKeyManager, get_zai_key_manager
from .config import (
    ModelConfig,
    ModelPreset,
    get_preset_for_use_case,
    get_model_params,
    get_fallback_chain,
    get_model_by_id,
    get_models_by_provider,
    get_models_by_category,
    is_model_supported_for_use_case,
    AVAILABLE_MODELS,
    CHATBOT_PRESET,
    RESEARCH_PRESET,
    EXTRACTION_PRESET,
    MERGE_PRESET,
    REPORT_PRESET,
    COMPRESSION_PRESET,
    GROQ_QWEN3_32B,
    GROQ_LLAMA_70B,
    GROQ_LLAMA_8B,
    MINIMAX_M27,
    ZAI_GLM_47_FLASH,
)

__all__ = [
    "LLMService",
    "GroqKeyManager",
    "get_groq_key_manager",
    "ZAIKeyManager",
    "get_zai_key_manager",
    "LLMError",
    "LLMRateLimitError",
    "LLMQuotaExceededError",
    "LLMContextWindowError",
    "quick_completion",
    "ModelConfig",
    "ModelPreset",
    "get_preset_for_use_case",
    "get_model_params",
    "get_fallback_chain",
    "get_model_by_id",
    "get_models_by_provider",
    "get_models_by_category",
    "is_model_supported_for_use_case",
    "AVAILABLE_MODELS",
    "CHATBOT_PRESET",
    "RESEARCH_PRESET",
    "EXTRACTION_PRESET",
    "MERGE_PRESET",
    "REPORT_PRESET",
    "COMPRESSION_PRESET",
    "GROQ_QWEN3_32B",
    "GROQ_LLAMA_70B",
    "GROQ_LLAMA_8B",
    "MINIMAX_M27",
    "ZAI_GLM_47_FLASH",
]
